GG-29901 Implement readiness probe REST endpoint
gridgain/gridgain pull request #1426
Opened 2020-09-14 15:35 UTC by akorensh

2020-10-19 22:14 UTC, akorensh commented on modules/core/src/main/java/org/apache/ignite/internal/processors/rest/handlers/probe/GridProbeCommandHandler.java
> +                        Thread.sleep(1000L);
implemented -- see latest pull request.
<p> Using startLatch status to determine whether kernal has started. </p>

Test checks whether this works:
      <p>1. start the grid on a seperate thread w/a plugin that will keep it waiting, at a point after rest http processor is ready, until signaled to proceed. </p>
      <p>2. when the grid.start() has reached the plugin init method(rest http processor has started now), issue a rest command against the non-fully started kernal. </p>
      <p>3. validate that the probe cmd has returned the appropriate erroneous code and message. </p>

2020-10-28 15:14 UTC, slukyano requested changes
Please fix the one typo highlighted and proceed with merge

2020-10-28 15:14 UTC, slukyano commented on modules/rest-http/src/test/java/org/apache/ignite/internal/processors/rest/protocols/http/jetty/GridProbeCommandTest.java
> +    public static Map<String, Object> exectuteProbeRestRequest() throws IOException {
```suggestion
    public static Map<String, Object> executeProbeRestRequest() throws IOException {
```

2020-10-28 15:19 UTC, slukyano requested changes

2020-10-28 15:19 UTC, slukyano commented on modules/core/src/main/java/org/apache/ignite/internal/processors/rest/GridRestResponse.java
> +    //** HTTP REQUEST not allowed */
```suggestion
    /** HTTP REQUEST not allowed */
```

2020-10-28 15:19 UTC, slukyano commented on modules/core/src/main/java/org/apache/ignite/internal/processors/rest/GridRestResponse.java
> +    public static final int SC_FORBIDDEN = 403;
better to use 503 "SERVICE UNAVAILABLE"

2020-10-29 14:36 UTC, merged

2020-10-29 14:37 UTC, akorensh commented on modules/core/src/main/java/org/apache/ignite/internal/processors/rest/GridRestResponse.java
> +    public static final int SC_FORBIDDEN = 403;
done.