Gg 24792
gridgain/gridgain pull request #1439
Opened 2020-09-23 08:41 UTC by denis-chudov

2020-09-23 09:08 UTC, zstan commented on modules/core/src/test/java/org/apache/ignite/testframework/MessageWaitingLogListener.java
> +}
no new line, not a bug but check would not blinked )

2020-10-01 12:21 UTC, sergey-chugunov-1985 requested changes

2020-10-01 12:21 UTC, sergey-chugunov-1985 commented on modules/core/src/test/java/org/apache/ignite/testframework/MessageWaitingLogListener.java
> + */
Minor code style: new line between license header and first line of code is missing.

2020-10-01 12:21 UTC, sergey-chugunov-1985 commented on modules/core/src/test/java/org/apache/ignite/testframework/MessageWaitingLogListener.java
> +    private final CountDownLatch latch = new CountDownLatch(1);
Do we want to specify number of messages we gonna wait for? I think it may be useful in other tests to wait for several similar messages.

2025-11-27 18:21 UTC, closed without merging