GG-31129 Cache metrics without description
gridgain/gridgain pull request #1521
Opened 2020-10-28 07:27 UTC by vmalin

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("Number estimated to rebalance keys.")
_Estimated total number of keys to rabalance._

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("The number of partitions need to be cleared before actual rebalance start.")
The number of partitions to be cleared before actual rebalance start_s_.

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("The percentage of invocations on keys, which exist in cache.")
The percentage of invocations on keys which[comma not needed] exist in _the_ cache.

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("The total number of invocations on keys, which exist in cache.")
The total number of invocations on keys[comma not needed] which exist in _the_ cache.

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("The total number of invocations on keys, which don't exist in cache.")
The total number of invocations on keys[comma not needed] which don't exist in _the_ cache.

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("The percentage of invocations on keys, which don't exist in cache.")
The percentage of invocations on keys[comma not needed] which don't exist in _the_ cache.

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("The total number of cache invocations, caused update.")
The total number of cache invocations _which_ caused _an_ update.

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("The total number of cache invocations, caused no updates.")
The total number of cache invocations _which_ caused no updates.

2020-10-28 08:09 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("The total number of cache invocations, caused removal.")
The total number of cache invocations _which_ caused _a_ removal.

2020-11-09 11:58 UTC, alievmirza requested changes

2020-11-09 11:58 UTC, alievmirza commented on modules/core/src/main/java/org/apache/ignite/mxbean/CacheMetricsMXBean.java
> +    @MXBeanDescription("Estimated total number of keys to rabalance.")
rabalance -> rebalance

2020-12-16 02:36 UTC, merged