GG-21977 Parameters that can be configured via TransactionsMXBean do not propagate to newly joined nodes
gridgain/gridgain pull request #1545
Opened 2020-11-02 20:02 UTC by makedonskaya

2020-11-06 11:26 UTC, vmalin commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridTransactionsSystemUserTimeMetricsTest.java
> +        return applyJmxParameters(threshold, coefficient, limit, tmMxBean, (IgniteEx) client);
Maybe it's better to change _client_ type to IgniteEx on definition?

2020-11-06 11:26 UTC, vmalin commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/GridTransactionsSystemUserTimeMetricsTest.java
> +        applyJmxParameters(1000L, 0.0, 6);
Was this change actually needed?

2020-11-06 11:26 UTC, vmalin commented on modules/core/src/main/java/org/apache/ignite/internal/cluster/DistributedTransactionConfiguration.java
> +    public GridFutureAdapter<?> updateTransactionTimeDumpSamplesCoefficientAsync(double transactionTimeDumpSamplesCoefficient) throws IgniteCheckedException {
Here and below: too long line. Personally, I'm ok with it but formally it's a code style violation

2021-04-12 07:47 UTC, alievmirza requested changes

2021-04-12 07:47 UTC, alievmirza commented on modules/core/src/main/java/org/apache/ignite/internal/cluster/DistributedTransactionConfiguration.java
> +     * @return Threshold timeout for long transactions.
Please add here and in other places corresponding links to full java doc like {@link DistributedTransactionConfiguration#longTransactionTimeDumpThreshold}

2021-04-12 07:47 UTC, alievmirza commented on modules/core/src/test/java/org/apache/ignite/internal/TransactionsMXBeanImplTest.java
> +     * Test to verify the correct change of "The coefficient for samples of completed transactions
Please use something like {@link #getTransactionTimeDumpSamplesCoefficient} instead of phrases in quotes

2021-05-06 00:42 UTC, alievmirza commented on modules/core/src/main/java/org/apache/ignite/internal/cluster/DistributedTransactionConfiguration.java
> +                        longOperationsDumpTimeout.localUpdate(dfltLongOpsDumpTimeout);
let's add some warning message here, like `log.warning("Distributed metastorage is not supported." + some useful info about local update`

2021-05-06 00:42 UTC, alievmirza commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +            IgniteRunnable closure,
let's use abbreviation here

2021-08-13 09:36 UTC, closed without merging