GG-32342 Add time of first page fetching.
gridgain/gridgain pull request #1760
Opened 2021-02-05 14:45 UTC by vsisko

2021-02-08 02:17 UTC, nva reviewed
Can we add a tests for this?

2021-02-08 12:18 UTC, wirtsleg requested changes
68 line:
> long start = U.currentTimeMillis();

Let's change it to `System.currentTimeMillis()` too.

2021-02-08 15:51 UTC, vsisko commented
Changing getting of current time from IgniteUtils to System. Added test.

2021-02-09 02:47 UTC, nva approved these changes

2021-02-09 13:43 UTC, wirtsleg approved these changes

2021-02-10 13:16 UTC, merged