GG-19456 Fix TestCafe tests.
gridgain/gridgain pull request #177
Opened 2019-06-20 11:07 UTC by nva

2019-06-20 12:23 UTC, akuznetsov-gridgain approved these changes
Looks good to me.
Please take a look at my minor comments.

2019-06-20 12:23 UTC, akuznetsov-gridgain commented on modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/services/AdminService.java
>       */
Add "@return" to javadocs.

2019-06-20 12:23 UTC, akuznetsov-gridgain commented on modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/web/controller/RestExceptionHandler.java
> +        return handleExceptionInternal(ex, new ErrorResponse(NOT_FOUND, "Account with email does not exists: " + ex.getMessage()), null, NOT_FOUND, req);
Split this line in two.

2019-06-21 03:16 UTC, nva commented on modules/web-console/web-console-server/src/main/java/org/apache/ignite/console/services/AdminService.java
>       */
method does not return nothing

2019-06-21 08:10 UTC, Klaster1 requested changes

2019-06-21 11:52 UTC, Klaster1 requested changes

2019-06-21 11:52 UTC, Klaster1 commented on docker/web-agent/README.txt
> +Ready image will be available in local docker registry (can be seen by calling the `docker images` command)
>Ready image

The image

2019-06-21 11:52 UTC, Klaster1 commented on modules/web-console/docker/console/README.txt
> +Ready image will be available in local docker registry (can be seen by calling the `docker images` command)
>Ready image

The image

2019-06-24 02:36 UTC, nva commented on modules/web-console/e2e/testcafe/environment/envtools.js
> +const dropTestDB = () => {
This method removes test users by mask. I don't want to rename this method, because this is huge change.

2019-06-24 02:37 UTC, nva commented on modules/web-console/DEVNOTES.txt
> +3. Properties in /config subdirectory of the work directory or in work directory (application.properties and YAML variants).
current work directory

2019-06-24 04:07 UTC, Klaster1 commented on modules/web-console/DEVNOTES.txt
> +3. Properties in /config subdirectory of the work directory or in work directory (application.properties and YAML variants).
I suggest you change wording here to prevent further confusion.

2019-06-24 11:03 UTC, imurchenko requested changes

2019-06-25 10:46 UTC, Klaster1 approved these changes
I have no more complaints. Docker images build and run without further issues, running local fixtures against backend/frontend in Docker works too.

2019-06-26 04:34 UTC, Klaster1 approved these changes

2019-06-26 09:56 UTC, Klaster1 approved these changes

2019-06-26 18:00 UTC, imurchenko approved these changes
Looks good to me.

2019-06-27 03:57 UTC, Klaster1 approved these changes

2019-06-27 07:01 UTC, Klaster1 approved these changes

2019-06-28 03:05 UTC, Klaster1 approved these changes

2019-06-28 09:11 UTC, merged