GG-33016 [IGNITE-14402] Java thin client: Continuous queries support
gridgain/gridgain pull request #1881
Opened 2021-04-15 09:41 UTC by ptupitsyn

Co-authored-by: Aleksey Plekhanov <plehanov.alex@gmail.com>

2021-04-15 10:02 UTC, isapego requested changes
See my comments inline

2021-04-15 18:17 UTC, ptupitsyn commented on modules/core/src/main/java/org/apache/ignite/client/ClientDisconnectListener.java
> + * Copyright 2019 GridGain Systems, Inc. and Contributors.
Fixed

2021-04-15 18:20 UTC, ptupitsyn commented on modules/core/src/main/java/org/apache/ignite/client/ClientDisconnectListener.java
> +     * @param reason Exception that caused the disconnect, can be {@code null}.
Done

2021-04-16 08:37 UTC, isapego approved these changes
Looks good to me

2021-04-16 08:38 UTC, merged