GG-34170 C++ thin: SSL certificates, keys and CA are not mandatory
gridgain/gridgain pull request #2286
Opened 2022-01-20 10:46 UTC by isapego

2022-01-20 12:04 UTC, ptupitsyn requested changes

2022-01-20 14:27 UTC, isapego commented on modules/platforms/cpp/network/src/network/ssl/secure_utils.cpp
> +            ThrowSecureError("Can not set default Certificate Authority for secure connection. Try setting custom CA");
The problem is, the same library is used for ODBC and thin client and API is different for them.

2022-01-20 14:29 UTC, isapego commented on modules/platforms/cpp/network/src/network/ssl/secure_utils.cpp
> +                        ThrowSecureError("Can not set Certificate Authority path for secure connection");
Will do

2022-01-20 14:42 UTC, isapego commented on modules/platforms/cpp/network/src/network/ssl/secure_utils.cpp
> +            ThrowSecureError("Can not create X509_STORE certificate store. Try setting custom CA");
Not sure how to handle error here properly. Documentation says nothing about diagnostics and there is a high chance there will be "No error" if we just look into error stack.

2022-01-21 06:50 UTC, ptupitsyn approved these changes
Looks good to me.

Can we add any tests for the new error handling code?

2022-01-21 14:51 UTC, merged