GG-35088  Make nodes more resilient in case of a job cancellation
gridgain/gridgain pull request #2405
Opened 2022-04-18 08:53 UTC by tkalkirill

https://ggsystems.atlassian.net/browse/GG-35088

2022-04-27 08:30 UTC, sergey-chugunov-1985 commented on modules/core/src/main/java/org/apache/ignite/internal/processors/job/GridJobWorkerInterrupter.java
> +public class GridJobWorkerInterrupter implements GridTimeoutObject {
I suggest another name: how about GridJobWorkerInterruptionTimer?

2022-04-27 08:32 UTC, sergey-chugunov-1985 commented on modules/core/src/main/java/org/apache/ignite/internal/util/worker/GridWorker.java
> +    protected void onCancel(boolean first) {
Don't like the name of the parameter. `firstCancelAttempt` or `firstCancelled` would be better.

2022-04-27 08:36 UTC, sergey-chugunov-1985 commented on modules/core/src/test/java/org/apache/ignite/internal/GridFailoverCustomTopologySelfTest.java
> +            // We change it because compute jobs will fall asleep.
`will go to sleep`.

2022-04-27 08:43 UTC, sergey-chugunov-1985 commented on modules/core/src/test/java/org/apache/ignite/internal/GridMultithreadedJobStealingSelfTest.java
> +        // We are changing it because compute jobs fall asleep.
`go to sleep`

2022-04-27 09:06 UTC, sergey-chugunov-1985 requested changes

2022-04-27 09:10 UTC, tkalkirill commented on modules/core/src/main/java/org/apache/ignite/internal/processors/job/GridJobWorkerInterrupter.java
> +public class GridJobWorkerInterrupter implements GridTimeoutObject {
What about **GridJobWorkerTimeoutInterrupter** ?

2022-04-27 09:21 UTC, tkalkirill commented on modules/core/src/test/java/org/apache/ignite/internal/processors/compute/InterruptComputeJobTest.java
> +            jobWorker = n.context().job().passiveJob(jobId);
I'll change it, no problem.

2022-04-27 11:15 UTC, tkalkirill commented on modules/core/src/test/java/org/apache/ignite/internal/processors/compute/ComputeJobStatusTest.java
> +            U.sleep(100);
I propose to leave it as it is, because on Windows there are problems in the gronularity of the timers.

2022-04-28 14:12 UTC, sergey-chugunov-1985 commented on modules/core/src/test/java/org/apache/ignite/internal/processors/compute/ComputeJobStatusTest.java
> +            U.sleep(100);
Makes sense, let leave this sleep as it seems to be unavoidable.

2022-04-28 14:21 UTC, sergey-chugunov-1985 requested changes

2022-04-28 14:21 UTC, sergey-chugunov-1985 commented on modules/core/src/main/java/org/apache/ignite/internal/processors/job/GridJobWorkerInterruptTimeoutObject.java
> +public class GridJobWorkerInterruptTimeoutObject implements GridTimeoutObject {
`JobWorkerInterruptionTimeoutObject` - lets stick to this name. I don't see a lot of value in `Grid` prefix, and `Interruption` sounds more intuitive to me.

2022-04-29 09:20 UTC, merged