GG-35833 Fixed an issue that could lead to incorrect cache metrics calculation after re-activation a cluster
gridgain/gridgain pull request #2619
Opened 2022-11-02 13:47 UTC by sk0x50

https://ggsystems.atlassian.net/browse/GG-35833

2022-11-09 14:44 UTC, kgusakov requested changes

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method do nothing in case a metric with the given name already exists.
```suggestion
     * This method does nothing in case a metric with the given name already exists.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method do nothing in case a metric with the given name already exists.
```suggestion
     * This method does nothing in case a metric with the given name already exists.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method do nothing in case a metric with the given name already exists.
```suggestion
     * This method does nothing in case a metric with the given name already exists.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method is equivalent to, for this
to what?

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method is equivalent to, for this
to what?

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method do nothing in case a metric with the given name already exists.
```suggestion
     * This method does nothing in case a metric with the given name already exists.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * @return registred metric.
```suggestion
     * @return registered metric.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * @return registred metric.
```suggestion
     * @return registered metric.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * @return registred metric.
```suggestion
     * @return registered metric.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * @return registred metric.
```suggestion
     * @return registered metric.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * @return registred metric.
```suggestion
     * @return registered metric.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * @return registred metric.
```suggestion
     * @return registered metric.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * @return registred metric.
```suggestion
     * @return registered metric.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method is equivalent to, for this
Please, fix here and in another comments

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method do nothing in case a metric with the given name already exists.
```suggestion
     * This method does nothing in case a metric with the given name already exists.
```

2022-11-09 14:44 UTC, kgusakov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +     * This method do nothing in case a metric with the given name already exists.
Please, fix another places too

2022-11-15 09:44 UTC, sk0x50 commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheMetricsImpl.java
> +        mreg.replaceOrRegister("IsIndexRebuildInProgress", () -> {
Removed duplicated metric

2022-11-15 09:44 UTC, sk0x50 commented on modules/core/src/main/java/org/apache/ignite/internal/processors/metric/MetricRegistry.java
> +    public BooleanGauge replaceOrRegister(String name, BooleanSupplier supplier, @Nullable String desc) {
Thanks, Renamed

2022-11-15 13:38 UTC, kgusakov approved these changes

2022-11-15 18:33 UTC, closed without merging