GG-36352 -Enhance error handling in GridMapQueryExecutor with detailed logging
gridgain/gridgain pull request #3359
Opened 2024-12-15 01:27 UTC by dy2285

https://ggsystems.atlassian.net/browse/GG-36352

- Implemented logQueryDetails method for centralized error logging.
- Integrated logQueryDetails into key error-handling blocks in GridMapQueryExecutor.
- Added unit tests:
`testLogQueryDetailsDirectly`
`testLogQueryDetailsWithNullInputs`
`testLogQueryDetailsOnQueryFailure`

2025-02-02 08:44 UTC, dy2285 commented
Hi Ilya @solveme 
Please review only the last commit (07e01a2).The previous commits were part of the development process and should not be considered separately.

Summary of Changes:
- Implemented `logQueryDetails` method for centralized error logging.
- Integrated `logQueryDetails` into query execution error handling.
- Addressed previous feedback by removing redundant logging.
- Added an integration test to verify logged messages.
- Successfully tested in both local IDE and TeamCity.

Notes:
- Branch blocker VISA issue unresolved (see Slack discussion)

2025-04-07 14:58 UTC, stasusov commented on checkstyle/checkstyle.xml
> +    <module name="SuppressionFilter">
Why did you add this? What's the reason or issue you were fixing with this?

2025-04-14 15:13 UTC, dy2285 commented on checkstyle/checkstyle.xml
> +    <module name="SuppressionFilter">
This was unintentionally added while troubleshooting local checkstyle violations. It’s been reverted since — not part of the final change.

2025-04-16 18:13 UTC, solveme requested changes

2025-04-16 18:13 UTC, solveme commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                .append("\nParameters: ").append(params != null ? Arrays.toString(params) : "N/A")
I've just realized that dumping query arguments might not be desirable behavior (from security perspective). If user want to see params he should explicitly allow it.

We can use same approach that is used in `BinaryObjectImpl.toString()`, i.e.:

    if (params == null)
        .append("\nParameters: N/A")
    else {
        boolean secureParams = S.getSensitiveDataLogging() != PLAIN;
        .append("\nParameters: ")
        .append(secureParams ? "HIDDEN" : Arrays.toString(params))
    }

2025-04-16 18:13 UTC, solveme commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                                log.error(errMsg, e);
Let's use construction like:

    U.error(log, errMsg, e);

To guarantee that we won't lose this message in case if logging was not properly configured by user

2025-04-16 18:13 UTC, solveme commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +}
Add an empty line at the end

2025-04-17 13:53 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                .append("\nParameters: ").append(params != null ? Arrays.toString(params) : "N/A")
Replaced the original `params` appending line with the suggested conditional block that checks `S.getSensitiveDataLogging()`. Thanks for highlighting the security consideration!

2025-04-17 13:54 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                .append("\nTimestamp: ").append(System.currentTimeMillis())
Removed the timestamp line — makes sense to rely on the logger’s built-in timestamp. Thanks!

2025-04-17 13:55 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                                log.error(errMsg, e);
Updated both logging branches to use `U.error(log, errMsg, e)` as suggested — ensures message won’t be lost due to misconfigured logger.

2025-04-17 13:56 UTC, dy2285 commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +public class GridMapQueryExecutorTest {
Refactored the test class to remove unnecessary mocks and dependency wiring. Since `buildQueryLogDetails()` is now a pure function,  I've simplified the setup and made all tests standalone.

2025-04-17 13:57 UTC, dy2285 commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +}
Added the trailing newline as part of the test class cleanup. Thanks for the catch!

2025-04-18 21:26 UTC, solveme reviewed
LGTM

2025-04-18 23:59 UTC, ibelyakov requested changes
See comments.

2025-04-18 23:59 UTC, ibelyakov commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                            String errMsg = buildQueryLogDetails(reqId, label, schemaName, qrys, params, e, node.id(),ctx.localNodeId());
There should be a space between "node.id()," and "ctx.localNodeId()". Also, the line seems to be pretty long, please consider splitting it into two.

2025-04-18 23:59 UTC, ibelyakov commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +    protected void onQueryRequest0(
I believe we can keep it "private" since there are no usages for this method by any other class besides GridMapQueryExecutor.

2025-04-18 23:59 UTC, ibelyakov commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> + * Copyright 2019 GridGain Systems, Inc. and Contributors.
Should be 2025

2025-04-18 23:59 UTC, ibelyakov commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                        queries != null
I suppose that the `queries` collection could be empty, so let's use `!F.isEmpty(queries)` here instead

2025-04-18 23:59 UTC, ibelyakov commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +
Let's remove the empty string.

2025-04-18 23:59 UTC, ibelyakov commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                            else {
There is no point in adding "else" here. Also, let's change the logging level back to WARN here, since it was intentionally downgraded sometime ago as part of GG-34383.

2025-04-19 00:09 UTC, ibelyakov commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +            logMessage.append("\nError: ").append(error.getMessage());
Do we need to add error.getMessage() into the message here? Won't it be printed in the log anyway as a part of U.error(log, errMsg, e); execution?

2025-04-21 02:09 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                        queries != null
Thanks! Switched to !F.isEmpty(queries) as suggested. Much cleaner and safer.

2025-04-21 02:09 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +            logMessage.append("\nError: ").append(error.getMessage());
Makes sense — removed the explicit getMessage() call since it's already included in U.error(...). Thanks!

2025-04-21 02:10 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +
Removed the dangling empty string after dropping getMessage() — thanks for pointing that out.

2025-04-21 02:13 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +    protected void onQueryRequest0(
Reverted to `private` — It was changed to protected earlier when this was extracted as a method. After inlining back to a function inside the same class, `private` is sufficient again.

2025-04-21 02:14 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                            String errMsg = buildQueryLogDetails(reqId, label, schemaName, qrys, params, e, node.id(),ctx.localNodeId());
Added a space and split long line for clarity as suggested.

2025-04-21 02:14 UTC, dy2285 commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> + * Copyright 2019 GridGain Systems, Inc. and Contributors.
Updated year to 2025.

2025-04-21 23:31 UTC, ibelyakov approved these changes
LGTM

2025-04-23 23:56 UTC, ashapkin commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +            logMessage.append("\nError: ");
Something is broken here. Why do we need "error" obj in this method? 
Do tests pass? It looks like here we are expecting to pring the error message.

2025-04-24 15:01 UTC, dy2285 commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +            logMessage.append("\nError: ");
This if (error != null) block was originally meant to include error.getMessage(), but we removed that earlier due to redundancy (since the full throwable is logged right after). Since you pointed it out, I re-evaluated and agree that logging just the label without content isn’t useful. For clean and clear logging, it's better to rely on the logging framework’s built-in exception handling — so I’ve removed the block entirely for clarity.

2025-06-30 16:19 UTC, solveme requested changes
@dy2285 let's extract params stringification ot separate method in order to simplify the code a bit and to get rid of `"params="` duplications.

Also let's add one more test that I mentioned.

2025-06-30 16:19 UTC, solveme commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +        String paramsStr;
Let's extract paramString resolution to separate utility method (i.e. `String stringifyParams(Object[] params)`). This will help us to get rid of `paramsStr` variable because use it only once in final formatting. So this method can be a pure function like:

    String stringifyParams(Object[] params) {
        if (params == null || params.length == 0)
            return "N/A";    // It's safe to tell that there were no params

        switch (S.getSensitiveDataLogging()) {
            case NONE:
                return "HIDDEN";
            case HASH:
                return String.valueOf(IgniteUtils.hash(Arrays.hashCode(params)));
            case PLAIN:
            default:
                return Arrays.toString(params);
        }    
    }

2025-06-30 16:19 UTC, solveme commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +        SensitiveDataLogging sensitivity = S.getSensitiveDataLogging();
Let's move it closer to the place where it used. Probably we can even inline it, see my post about separate method below.

2025-06-30 16:19 UTC, solveme commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                    paramsStr = "params=HIDDEN";
We apready have `" ... params=%s ..."` in the final formatting, no need to add `params=` here

2025-06-30 16:19 UTC, solveme commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                    paramsStr = "params=" + Arrays.stream(params)
We can't hash each element because if has code of some types like integers is the number itself, so I can try to infer original param value from `Integer.toHexString(Objects.hashCode(p))` especially if it's clear from the query string that iven column is integer || short || byte. 

So what we should do is to calculate the hash of the whole params array. See my previous comment with sample. As we discussed the goal of having hash code is to evaluate whether given query always fail with same params or not. So proposed technique is enough for that.

2025-06-30 16:19 UTC, solveme commented on modules/indexing/src/main/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutor.java
> +                    paramsStr = "params=" + Arrays.toString(params);
Again redundant "params="

2025-06-30 16:19 UTC, solveme commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +        assertTrue(logContent.contains("params=params=HIDDEN"));
`params=params=HIDDEN` :smile:

2025-06-30 16:19 UTC, solveme commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +    }
Let's add one more tests where params array has some content. Let's say `(int) 42, null, "foo", (double)3.14`, etc..

2025-07-02 08:57 UTC, solveme requested changes
Left a comment about test adjustments

2025-07-02 08:57 UTC, solveme commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +        assertTrue(log.contains("params="));
The goal of this test was to check that we properly dump params depending on sensitivity value, so best way is to   wrap body of this ticket to separate method which accepts Sensitivity value and expected params ie.. 

    private static testBuildQueryLogDetailsWithSampleParams(String sensitivity, String expectedParams) {
        System.setProperty(IgniteSystemProperties.IGNITE_SENSITIVE_DATA_LOGGING, sensitivity);
        
        Collection<GridCacheSqlQuery> queries = Collections.singletonList(
            new GridCacheSqlQuery("SELECT * FROM test")
        );
        
        ....
        
        assertTrue(log.contains("params=" + expectedParams));
    }

Then you can reuse it for testing all sensitivity cases, i.e.:

    @Test
    public testBuildQueryLogDetailsWithPlainSensitivity(String sensitivity, String expectedParams) {
        testBuildQueryLogDetailsWithSampleParams("plain", "[...]")
    }

2025-07-02 08:57 UTC, solveme commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +    private final GridMapQueryExecutor executor = new GridMapQueryExecutor();
It looks like this variable is not used anywhere, if that so, let's remove it

2025-07-03 09:07 UTC, solveme requested changes

2025-07-03 09:07 UTC, solveme commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +    public void testBuildQueryLogDetailsWithSampleParams(String sensitivity, String expectedParams) {
It's better to not hardcode params value in the method body, but rather accept it as parameter, because it will make things much more obvious at the callsite. I.e. we pass following params and we expect to see following result.

P.S. I remember that It was me, who suggested such signature. Sorry if I confused you, but don't threat my code samples as perfect :smile: by default.

2025-07-03 09:07 UTC, solveme commented on modules/indexing/src/test/java/org/apache/ignite/internal/processors/query/h2/twostep/GridMapQueryExecutorTest.java
> +        int hash = Arrays.hashCode(new Object[]{42, "john", 345});
As was highlighted above, it's better to have something like

    Object[] givenParams = new Object[]{42, "john", 345};
    String expectedOutput = String.valueOf(Arrays.hashCode(givenParams));
    testBuildQueryLogDetailsWithSampleParams("hash", givenParams, expectedOutput);

Please adjust sensitivity-related methods in this way.

2025-07-03 15:59 UTC, solveme approved these changes
LGTM

2025-07-03 16:33 UTC, merged